const GlobalAssets: any = {
  "logo-eth": "/assets/logo/ethereum-eth-logo.svg",
  "logo-base": "/assets/logo/base-logo.svg",
  "logo-polygon": "/assets/logo/polygon-matic-logo.svg",
  "logo-lighthouse": "",
  "logo-filecoin": "/assets/logo/filecoin-logo.svg",
  "logo-optimism": "/assets/logo/optimism-logo.svg",
  "logo-solana": "/assets/logo/solana-logo.svg",
  "logo-cardano": "/assets/logo/cardano-logo.svg",
  "logo-nftstorage": "/assets/logo/nftstorage-logo.svg",
  "logo-openSea": "/assets/logo/openSea-logo.svg",
  "logo-rarible": "/assets/logo/rarrible-logo.svg",
  "logo-tatum": "/assets/logo/tatum-logo.svg",
  "logo-stargaze": "/assets/logo/stargaze-logo.jpg",
  "logo-zksync": "/assets/logo/zksync-logo.svg",
  "logo-immutable": "/assets/logo/immutable-logo.svg",
  "logo-arbitrum": "/assets/logo/arbitrum-logo.svg",
  "logo-algorand": "/assets/logo/algorand-logo.svg",
  "logo-avalanche": "/assets/logo/avalanche-logo.svg",
  "logo-rari": "/assets/logo/rari-logo.svg",
  "logo-tezos": "/assets/logo/tezos-logo.svg",
  "logo-flow": "/assets/logo/flow-logo.svg",
  "logo-zora": "/assets/logo/zora-logo.png",
  "logo-ape": "/assets/logo/ape-logo.svg",
  "logo-blast": "/assets/logo/blast-logo.svg",
  "logo-cronos": "/assets/logo/cronos-logo.svg",
  "logo-hedera": "/assets/logo/hedera-logo.svg",
  "logo-mint": "/assets/logo/mint-logo.svg",
  "logo-shape": "/assets/logo/shape-logo.svg",
  "logo-xrpl": "/assets/logo/XRPL-logo.svg",
  "logo-xahau": "/assets/logo/xahau-logo.svg",
  "logo-sui": "/assets/logo/sui-logo.svg",
  "logo-multiversx": "/assets/logo/multiversx-logo.svg",
  "logo-counterparty": "/assets/logo/counterparty-logo.svg",
  "auth-side": "/assets/auth-side.svg",

  "icon-github": "/assets/icons/github.svg",
  "icon-logout": "/assets/icons/logout-icon.svg",
  "icon-dashboard": "/assets/icons/dashboard-icon.svg",
  "icon-support": "/assets/icons/support-icon.svg",
  "icon-apiKey": "/assets/icons/apiKey-icon.svg",
  "icon-docs": "/assets/icons/docs-icon.svg",
  "icon-plus": "/assets/icons/plus-icon.svg",
  "icon-chain": "/assets/icons/chain-icon.svg",
  "icon-chevron-close": "/assets/icons/chevron-close-icon.svg",
  "icon-chevron-down": "/assets/icons/chevron-down-icon.svg",
  "icon-circle-download": "/assets/icons/circle-download-icon.svg",
  "icon-close": "/assets/icons/close-icon.svg",
  "icon-colored-check": "/assets/icons/colored-check.svg",
  "icon-complete": "/assets/icons/complete-icon.svg",
  "icon-queue": "/assets/icons/queue-icon.svg",
  "icon-error": "/assets/icons/error-icon.svg",
  "icon-colored-info": "/assets/icons/colored-info.svg",
  "icon-copy": "/assets/icons/copy-icon.svg",
  "icon-folder-upload": "/assets/icons/folder-upload-icon.svg",
  "icon-info": "/assets/icons/info-icon.svg",
  "icon-settings-gear": "/assets/icons/settings-gear-icon.svg",
  "icon-noToken": "/assets/icons/noToken-icon.svg",
  "icon-search": "/assets/icons/search-icon.svg",
  "icon-filter": "/assets/icons/filter-icon.svg",
  "icon-delete": "/assets/icons/delete-icon.svg",

  "spining-loader": "/assets/logo/spining-loader.svg",
};

export default GlobalAssets;
